In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
url=requests.get('https://www.scrapethissite.com/pages/forms/?page_num=6')

In [3]:
The_page=BeautifulSoup(url.text,'html')

In [4]:
print(The_page)

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="hockey">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
</p>
<hr/>
</div>
</div>
<div class="row search-area">
<div class="col-md-12 text-center">
<form action="/pages/forms/" class="form form-inline" method="GET">
<label for="q">
                                Search for Teams:
                            </label>
<input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
<input class="btn btn-primary" type="submit" value="Search"/>
</form>
<hr/>
</div>
</div><!--.row.search-area-->
<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Dallas Stars
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            26
                        </td>
<td class="losses">
                            42
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.317
                        </td>
<td class="gf">
                            227
                        </td>
<td class="ga">
                            280
                        </td>
<td class="diff text-danger">
                            -53
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            62
                        </td>
<td class="losses">
                            13
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.756
                        </td>
<td class="gf">
                            325
                        </td>
<td class="ga">
                            181
                        </td>
<td class="diff text-success">
                            144
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            30
                        </td>
<td class="losses">
                            44
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.366
                        </td>
<td class="gf">
                            240
                        </td>
<td class="ga">
                            304
                        </td>
<td class="diff text-danger">
                            -64
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Florida Panthers
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.5
                        </td>
<td class="gf">
                            254
                        </td>
<td class="ga">
                            234
                        </td>
<td class="diff text-success">
                            20
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.415
                        </td>
<td class="gf">
                            237
                        </td>
<td class="ga">
                            259
                        </td>
<td class="diff text-danger">
                            -22
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            24
                        </td>
<td class="losses">
                            40
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.293
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            302
                        </td>
<td class="diff text-danger">
                            -46
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            40
                        </td>
<td class="losses">
                            32
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.488
                        </td>
<td class="gf">
                            265
                        </td>
<td class="ga">
                            248
                        </td>
<td class="diff text-success">
                            17
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.451
                        </td>
<td class="gf">
                            215
                        </td>
<td class="ga">
                            202
                        </td>
<td class="diff text-success">
                            13
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            22
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.268
                        </td>
<td class="gf">
                            229
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            27
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.5
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            237
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Ottawa Senators
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            18
                        </td>
<td class="losses">
                            59
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.22
                        </td>
<td class="gf">
                            191
                        </td>
<td class="ga">
                            291
                        </td>
<td class="diff text-danger">
                            -100
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            45
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.549
                        </td>
<td class="gf">
                            282
                        </td>
<td class="ga">
                            208
                        </td>
<td class="diff text-success">
                            74
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            29
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.598
                        </td>
<td class="gf">
                            362
                        </td>
<td class="ga">
                            284
                        </td>
<td class="diff text-success">
                            78
                        </td>
</tr>
<tr class="team">
<td class="name">
                            San Jose Sharks
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            20
                        </td>
<td class="losses">
                            55
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.244
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            357
                        </td>
<td class="diff text-danger">
                            -105
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            34
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.39
                        </td>
<td class="gf">
                            219
                        </td>
<td class="ga">
                            248
                        </td>
<td class="diff text-danger">
                            -29
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Tampa Bay Lightning
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            38
                        </td>
<td class="losses">
                            32
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            248
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.415
                        </td>
<td class="gf">
                            247
                        </td>
<td class="ga">
                            252
                        </td>
<td class="diff text-danger">
                            -5
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            35
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.39
                        </td>
<td class="gf">
                            278
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            32
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.476
                        </td>
<td class="gf">
                            234
                        </td>
<td class="ga">
                            204
                        </td>
<td class="diff text-success">
                            30
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1995
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            40
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.439
                        </td>
<td class="gf">
                            275
                        </td>
<td class="ga">
                            291
                        </td>
<td class="diff text-danger">
                            -16
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Mighty Ducks of Anaheim
                        </td>
<td class="year">
                            1996
                        </td>
<td class="wins">

In [5]:
table_headers=The_page.find_all('th')

In [6]:
print(table_headers)

[<th>
                            Team Name
                        </th>, <th>
                            Year
                        </th>, <th>
                            Wins
                        </th>, <th>
                            Losses
                        </th>, <th>
                            OT Losses
                        </th>, <th>
                            Win %
                        </th>, <th>
                            Goals For (GF)
                        </th>, <th>
                            Goals Against (GA)
                        </th>, <th>
                            + / -
                        </th>]

In [7]:
headers=[header.text.strip()for header in table_headers]

In [8]:
print(headers)

['Team Name', 'Year', 'Wins', 'Losses', 'OT Losses', 'Win %', 'Goals For (GF)', 'Goals Against (GA)', '+ / -']

In [9]:
import pandas as pd
df=pd.DataFrame(columns=headers)

In [10]:
df

Empty DataFrame
Columns: [Team Name, Year, Wins, Losses, OT Losses, Win %, Goals For (GF), Goals Against (GA), + / -]
Index: []

In [12]:
table = The_page.find('table')

In [17]:
rows = table.find_all('tr')[1:]

for row in rows:
    table_final_data = [
        data.get_text(strip=True)
        for data in row.find_all('td')
    ]

    df.loc[len(df)] = table_final_data

In [20]:
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Dallas Stars,1995,26,42,,0.317,227,280,-53
1,Detroit Red Wings,1995,62,13,,0.756,325,181,144
2,Edmonton Oilers,1995,30,44,,0.366,240,304,-64
3,Florida Panthers,1995,41,31,,0.5,254,234,20
4,Hartford Whalers,1995,34,39,,0.415,237,259,-22
...,...,...,...,...,...,...,...,...,...
70,Mighty Ducks of Anaheim,1996,36,33,,0.439,245,233,12
71,Boston Bruins,1996,26,47,,0.317,234,300,-66
72,Buffalo Sabres,1996,40,30,,0.488,237,208,29
73,Calgary Flames,1996,32,41,,0.39,214,239,-25
74,Chicago Blackhawks,1996,34,35,,0.415,223,210,13

In [23]:
df.to_csv(r'C:\Desktop Material\My Projects for GitHub\Web_Scrapping\Teams.csv',index=False)